apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-feed
  labels:
    app: backend-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api-feed
  template:
    metadata:
      labels:
        app: backend-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: justlee142/udagram-api-feed:v3
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET