version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          
      - run:
          name: Docker Login
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - run:
          name: Build Images
          command: |
            docker-compose -f docker-compose-build.yaml build

      - run:
          name: Tag Images
          command: | 
            docker tag udagram-api-user:latest $DOCKER_USERNAME/udagram-api-user:latest
            docker tag udagram-api-feed:latest $DOCKER_USERNAME/udagram-api-feed:latest
            docker tag udagram-frontend:latest $DOCKER_USERNAME/udagram-frontend:latest
            docker tag reverseproxy:latest $DOCKER_USERNAME/reverseproxy:latest

      - run:
          name: Push Images
          command: |
            docker push $DOCKER_USERNAME/udagram-api-user:latest
            docker push $DOCKER_USERNAME/udagram-api-feed:latest
            docker push $DOCKER_USERNAME/udagram-frontend:latest
            docker push $DOCKER_USERNAME/reverseproxy:latest           

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push:
          context: docker-hub-creds
