apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    service: frontend-service
spec:
  selector:
    service: frontend-service
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100